config/routes.rb
Rails.application.routes.draw do
  get 'find_pool/new'
  get 'find_pool/create'
  get 'find_pool', to: 'find_pool#find'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :cars
  resources :carpools



  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :login, only: [:index]

  root :to => "login#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html






end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user_id
  belongs_to :carpool_id
end

app/models/carpool.rb
class Carpool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #belongs_to :car_id, foreign_key: 'car_id', optional: true
  #belongs_to :carpool_id, foreign_key: 'carpool_id', optional: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/find_pool_controller.rb
class FindPoolController < ApplicationController
  def new
  end

  def create
  end

  def find
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

	def index
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :homeAdr, :destAdr, :maxDist, :car_id_id, :carpool_id_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_pool_helper.rb
module FindPoolHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/find_pool/findPool.html.erb
<%# This is the main application page.%>
<!DOCTYPE html>
<html>
  <head>
    <title>CRPL</title>  
    
    <%# Meta tags that are found in most regular HTML files %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# Linking the javascript and CSS files %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# Bootstrap CSS %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
    <%# Bootstrap JS %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  </head>

  <body>

    <div class="signInCustomContainer">
      <div id="signInToGoogle">
        <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
        <% end %>
      </div>
    </div>     
    
  </body>

</html>

app/views/layouts/application.html.erb
<%# This is the main application page.%>
<!DOCTYPE html>
<html>
  <head>
    <title>CRPL</title>  
    
    <%# Meta tags that are found in most regular HTML files %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# Linking the javascript and CSS files %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
 

    <%# Bootstrap CSS %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
    <%# Bootstrap JS %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#">CRPL</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="findPool.html">Find Pool<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Pools</a>
          </li>
          <li class="nav-item">
            <% if current_user %>
              <a class="nav-link" href="/<%= current_user.id %>/edit">Settings</a>
            <% else %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>  
    
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <%= yield %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>  
    </nav>   


  </body>

</html>

app/views/login/index.html.erb
<div class="signInCustomContainer">
  <div id="signInToGoogle">
    <% if current_user %>
      Signed in as <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
  </div>
</div>  

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
 <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :homeAdr %>
    <%= form.text_field :homeAdr %>
  </div>

  <div class="field">
    <%= form.label :destAdr %>
    <%= form.text_field :destAdr %>
  </div>

  <div class="field">
    <%= form.label :maxDist %>
    <%= form.number_field :maxDist %>
  </div>

  <div class="field">
    <%= form.label :car_id_id %>
    <%= form.text_field :car_id_id %>
  </div>

  <div class="field">
    <%= form.label :carpool_id_id %>
    <%= form.text_field :carpool_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

<div class="pageContainer">
    
    <div class="pageContainer">

        <div>

        <!-- First name -->
        <div class="singleSettingContainer">

            <p>Current First Name: <% current_user.fname %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

        <!-- Last name  -->
        <div class="singleSettingContainer">

            <p>Current Last Name: <% current_user.lname %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

        <!-- Home Address -->
        <div class="singleSettingContainer">

            <p>Current Default Home Address: <% current_user.homeAdr %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

        <!-- Target Address -->
        <div class="singleSettingContainer">

            <p>Current Default Destination: <% current_user.destAdr %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

        <!-- Max Distance -->
        <div class="singleSettingContainer">

            <p>Current Maximum Distance Away: <% current_user.maxDist %> Miles</p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

        <!-- Car Model -->
        <div class="singleSettingContainer">

            <p>Current Car Model: <% current_user.car_id_id %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>
s
            </form>

        </div>

        <!-- Car Seats -->
        <div class="singleSettingContainer">

            <p>Current # of Car Seats: <% current_user.car_id_id %> </p>
            <form>

                <input type="text">
                <button type="button">Submit</button>

            </form>

        </div>

    </div>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Homeadr</th>
      <th>Destadr</th>
      <th>Maxdist</th>
      <th>Car</th>
      <th>Carpool</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.homeAdr %></td>
        <td><%= user.destAdr %></td>
        <td><%= user.maxDist %></td>
        <td><%= user.car_id %></td>
        <td><%= user.carpool_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Homeadr:</strong>
  <%= @user.homeAdr %>
</p>

<p>
  <strong>Destadr:</strong>
  <%= @user.destAdr %>
</p>

<p>
  <strong>Maxdist:</strong>
  <%= @user.maxDist %>
</p>

<p>
  <strong>Car:</strong>
  <%= @user.car_id %>
</p>

<p>
  <strong>Carpool:</strong>
  <%= @user.carpool_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>